### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by asomers** [rbtcollins/effective-limits.rs#15]
Would it be possible to publish a new release?  That would allow rustup to fix https://github.com/rust-lang/rustup/issues/2629 .

**Comment by jclulow** [comment]
We would like to get cbad0df99db43a2dfa77398825cfab9a6f921d79 (rbtcollins/effective-limits.rs#11) into `rustup` as well so that we can fix the unpack buffer size detection issue on illumos there as well.  Would it be possible to get a new release, @rbtcollins ?  Thanks!

**Comment by rbtcollins** [comment]
yes - would like that too - last time we went to update this sys-info had incompatibilities. I'll have a look and see this weekend.

**Comment by Alovchin91** [comment]
Hi @rbtcollins I would also like to get #16 into rustup so that I could proceed with [Windows arm64 support](https://github.com/rust-lang/rustup/issues/2612). Would you please consider releasing a new version? 🙂

**Comment by kinnison** [comment]
I *think* the upstream changes (sys-info) are okay, so I'm going to push the button on releasing this version of effective-limits.  Hopefully I don't bugger anything up.

**Comment by kinnison** [comment]
v0.5.3 has been released.
